# Data Scientist with Python

- Introduction to Python
- Intermediate Python
- Python Data Science Toolbox (Part 1)
- Python Data Science Toolbox (Part 2)
- Importing Data in Python (Part 1)
- Importing Data in Python (Part 2)
- Cleaning Data in Python
- pandas Foundations
- Manipulating DataFrames with pandas
- Merging DataFrames with pandas
- Analyzing Police Activity with pandas
- Introduction to SQL
- Introduction to Relational Databases in SQL
- Introduction to Data Visualization with Python
- Interactive Data Visualization with Bokeh
- Statistical Thinking in Python (Part 1)
- Statistical Thinking in Python (Part 2)
- Joining Data in SQL
- Introduction to Shell
- Conda Essentials
- Supervised Learning with scikit-learn
- Machine Learning with the Experts: School Budgets
- Unsupervised Learning in Python
- Machine Learning with Tree-Based Models in Python
- Introduction to Deep Learning in Python
- Network Analysis in Python (Part 1)
